[dev]
    command = "yarn dev"
    autoLaunch = false
#[dev.https]
#    certFile = "localhost.pem"
#    keyFile = "localhost-key.pem"


[context.dev.environment]
    NODE_ENV = "development"
    PORT = "3000"
    # This is to make hot reloading works on live dev server
    HMR_PROTOCOL = "wss"

[context.production]
    NODE_ENV = "production"

# Specific branch context: all deploys from
# this specific branch will inherit these settings.
[context.staging] # “staging” is a branch name
    command = "echo 'staging'"
    base = "staging"


[[redirects]]
from = "/why-north-idaho-is-a-great-place-to-buy-land"
to = "/blog/why-north-idaho-is-a-great-place-to-buy-land"

[[redirects]]
from = "/north-idaho-a-destination-through-the-years"
to = "/blog/north-idaho-a-destination-through-the-years"

[[redirects]]
from = "/the-best-places-to-fish-in-north-idaho"
to = "/blog/the-best-places-to-fish-in-north-idaho"

[[redirects]]
from = "/hunting-in-north-idaho-a-guide-to-access-and-opportunities"
to = "/blog/hunting-in-north-idaho-a-guide-to-access-and-opportunities"

[[redirects]]
from = "/land-lot-inventory"
to = "/communities"

[[redirects]]
from = "/home-series"
to = "/our-homes"

[[redirects]]
from = "/timbered-ridge-homes/gallery*"
to = "/our-homes/gallery"

[[redirects]]
from = "/timbered-ridge-homes/custom-series*"
to = "/our-homes/custom"

[[redirects]]
from = "/timbered-ridge-homes/timbered-series*"
to = "/our-homes/timbered"

[[redirects]]
from = "/timbered-ridge-homes/ridge-series*"
to = "/our-homes/ridge"

[[redirects]]
from = "/images*"
to = "/our-homes/gallery"

[[redirects]]
from = "/timbered-ridge-homes/*"
to = "/"
